name: Deploy to Modal

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      MODAL_USER_NAME: ${{ secrets.MODAL_USER_NAME }}
      APP_NAME: ${{ secrets.MODAL_APP_NAME || 'proxy-app' }}
      SERVER_PORT: ${{ secrets.SERVER_PORT || 3000 }}
      
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 安装 Modal 客户端及必要的依赖
      - name: Install Modal
        run: pip install modal fastapi requests

      # 4. 认证 Modal
      - name: Authenticate Modal
        run: |
          modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      # 5. 停止任何已存在的同名应用
      - name: Stop Existing App (for clean deploy)
        run: |
          modal app stop ${{ env.APP_NAME }} || true

      # 6. 更新 Modal Secret
      - name: Create or Update Modal Secret
        run: |
          modal secret delete modal-secrets --yes || true
          
          modal secret create modal-secrets \
          UUID='${{ secrets.UUID }}' \
          MODAL_USER_NAME='${{ secrets.MODAL_USER_NAME }}' \
          ARGO_DOMAIN='${{ secrets.ARGO_DOMAIN }}' \
          ARGO_AUTH='${{ secrets.ARGO_AUTH }}' \
          ARGO_PORT='${{ secrets.ARGO_PORT }}' \
          SUB_PATH='${{ secrets.SUB_PATH }}' \
          NAME='${{ secrets.NAME }}' \
          CFIP='${{ secrets.CFIP }}' \
          CFPORT='${{ secrets.CFPORT }}' \
          NEZHA_SERVER='${{ secrets.NEZHA_SERVER }}' \
          NEZHA_KEY='${{ secrets.NEZHA_KEY }}' \
          NEZHA_PORT='${{ secrets.NEZHA_PORT }}' \
          UPLOAD_URL='${{ secrets.UPLOAD_URL }}' \
          PROJECT_URL='${{ secrets.PROJECT_URL }}' \
          BOT_TOKEN='${{ secrets.BOT_TOKEN }}' \
          CHAT_ID='${{ secrets.CHAT_ID }}'

      # 7. 部署 Modal 应用
      - name: Deploy to Modal
        run: modal deploy modal_app.py